package com.gym.app.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * PHASE 01E — ROOM DATABASE FOUNDATION
 *
 * Room persistence model for [com.gym.app.domain.model.UserProfile].
 *
 * This is a pure persistence concern: it mirrors the shape of the domain
 * model but is not the domain model itself. Mapping to/from
 * [com.gym.app.domain.model.UserProfile] happens exclusively through
 * `UserProfileMapper` (data/mapper), never inside the domain layer.
 *
 * [userId] is the primary key (not autogenerated): the domain model already
 * treats [userId] as the stable identity of a profile, and the app is being
 * built so this identifier can later back multiple local profiles, login,
 * or cloud sync — so Room should not invent its own separate identity.
 *
 * `gender` is stored as a nullable [String] (the enum's `name`) rather than
 * an ordinal, so reordering the `Gender` enum later cannot silently corrupt
 * already-persisted rows.
 */
@Entity(tableName = "user_profiles")
data class UserProfileEntity(
    @PrimaryKey
    val userId: String,
    val name: String,
    val age: Int,
    val gender: String?,
    val heightCm: Double,
    val currentWeightKg: Double,
    val experienceLevel: String,
    val activityLevel: String
)
